FROM apache/superset:latest
USER root

# 1. Установка драйверов Postgres
RUN /app/.venv/bin/python -m ensurepip --upgrade && \
    /app/.venv/bin/python -m pip install --no-cache-dir psycopg2-binary

USER superset