FROM apache/superset:latest
USER root

# 1. Установка драйверов Postgres
RUN /app/.venv/bin/python -m ensurepip --upgrade && \
    /app/.venv/bin/python -m pip install --no-cache-dir psycopg2-binary

# 2. Драйвер ClickHouse для слоя витрин (dm)
RUN /app/.venv/bin/python -m pip install --no-cache-dir "clickhouse-connect>=0.7.0"

USER superset